### ISSUE TITLE
matcher is undefined

### ISSUE THREAD

**Issue by schnie** [expandjs/expandjs#1]
Hey, I'm using `mat-icon-button` and `mat-menu-button` and just ran into an issue using firefox (works fine in chrome).  I'm getting an error on line 3282 of the built source. (https://github.com/expandjs/expandjs/blob/master/dist/expandjs.js#L3282)  saying `matcher is undefined`.  It seems like it is failing when it is looking up the svg in the iconsets for the icon I have specified, which should be good, since it works in chrome.  I'm not sure exactly why, but I was able to sort of get it working by adding the following before where its erroring out.

```
if (element.nodeName === "#text") {
  return false;
}
```

Any ideas?  Thanks!

**Comment by Pupix** [comment]
Thanks for the report!

We are working on it and a fix is coming very shortly. All components and libraries should be up and running by the end of the week at most.

In the meantime you can use Chrome as the main development platform, if it's not too much of a hassle for you.

**Comment by schnie** [comment]
Thanks for the quick reply!

**Comment by Pupix** [comment]
We've just got done with a new batch of updates. Your problem should be solved now.

Let me know if you encounter any other bugs.

**Comment by schnie** [comment]
Awesome!  Thanks!

**Comment by schnie** [comment]
Hmm, I think its still happening.  Just pulled down the latest and still getting the same error.  Only in firefox, chrome is good.

**Comment by Pupix** [comment]
Strange. Will let you know when there are more updates.

**Comment by Pupix** [comment]
Just tested it inside FF 36.0.4 and FFDE 40.0 and it works fine.

Used the following code:

``` html
<!DOCTYPE html>
<html>
    <head>
        <script src="../bower_components/webcomponentsjs/webcomponents-lite.js"></script>
        <link rel="import" href="../bower_components/polymer/polymer.html">
        <link rel="import" href="../bower_components/mat-icons/mat-icons.html">
        <link rel="import" href="../bower_components/mat-icon-button/mat-icon-button.html">
        <link rel="import" href="../bower_components/mat-menu-button/mat-menu-button.html">
    </head>
    <body>
        <mat-icon-button icon="social:person"></mat-icon-button>
        <mat-menu-button></mat-menu-button>
    </body>
</html>
```

Could you post your use case and the FF version you are using?

**Comment by schnie** [comment]
I'm using FF 38 on ubuntu.  I'm also using meteor.js and the built in blaze rendering library for my templates.  Maybe that's the problem.

**Comment by Pupix** [comment]
I am unable to reproduce this problem.

You may have a caching problem from bower, try to delete it and do a fresh install.

**Comment by Pupix** [comment]
Any progress? Got my hands on a FF on Ubuntu and still can't reproduce the problem, so it must be a caching problem.

**Comment by schnie** [comment]
Yea, maybe theres something going on with meteor.. thanks though!
